import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My app",
  description: "Generated by create next app. Test app.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper">
          <header className="row">
            <h1>global header</h1>
          </header>

          {children}

          <footer className="row">
            <h1>global footer</h1>
          </footer>
        </div>
      </body>
    </html>
  );
}
